language: go
go:
  - "1.14.x"

env:
  global:
    - CC_TEST_REPORTER_ID=ab820d8589d7911e494cf5de6524c80497e8df912bec0959320fc480c39225db

before_install:
  - go get github.com/rakyll/gotest
  - go get github.com/stretchr/testify/assert

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - gotest -v -coverprofile c.out ./...
  - go build ./graph ./stats

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT